// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXQl1MKFqi40eqaxQO90pjXQkJw3wSsc8',
    appId: '1:975438024042:web:c7d1d803ebf2389b2de913',
    messagingSenderId: '975438024042',
    projectId: 'template-flutter-27e96',
    authDomain: 'template-flutter-27e96.firebaseapp.com',
    storageBucket: 'template-flutter-27e96.appspot.com',
    measurementId: 'G-VS7MMJ3QD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDig6LGTD4Qj10zSk6G1QRW-eAZ1aQohVw',
    appId: '1:975438024042:android:6362660dc6c924332de913',
    messagingSenderId: '975438024042',
    projectId: 'template-flutter-27e96',
    storageBucket: 'template-flutter-27e96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7DrGms2UthEeBwD2q9Ei7c3Q6ChqSS58',
    appId: '1:975438024042:ios:46771b2d25bc37682de913',
    messagingSenderId: '975438024042',
    projectId: 'template-flutter-27e96',
    storageBucket: 'template-flutter-27e96.appspot.com',
    iosClientId: '975438024042-aabqfcrn5o98pupqud8g7qd5fs5td3iq.apps.googleusercontent.com',
    iosBundleId: 'com.upto.templateFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7DrGms2UthEeBwD2q9Ei7c3Q6ChqSS58',
    appId: '1:975438024042:ios:46771b2d25bc37682de913',
    messagingSenderId: '975438024042',
    projectId: 'template-flutter-27e96',
    storageBucket: 'template-flutter-27e96.appspot.com',
    iosClientId: '975438024042-aabqfcrn5o98pupqud8g7qd5fs5td3iq.apps.googleusercontent.com',
    iosBundleId: 'com.upto.templateFlutter',
  );
}
